---
title: ''
mainfont: PT Sans
documentclass: report
fontsize: 12pt  
classoption: landscape,twocolumn
geometry:
  margin=0.8in
header-includes:
   -
output: 
  pdf_document:
    latex_engine: xelatex
    fig_height: 0.3
    fig_width: 0.3
---
\pagenumbering{gobble} 
```{r setup, include=FALSE}
Sys.setlocale(,"UK_ua")
library(knitr)
  opts_chunk$set(fig.path='figure/graphics-', 
                 cache.path='cache/graphics-', 
                 fig.align='center',
                 external=TRUE,
                 echo=TRUE,
                 warning=FALSE,
                 fig.pos='H'
                )
  a4width<- 8.3
  a4height<- 11.7
library(tidyverse)
```

```{r, include=FALSE}
data <- readxl::read_excel("Зразок-для-закордонних-ЗМІ-16.06.2017.xlsx")
```

## `r data[15,5]`

`r data[12,4]`

`r data[13,4]`

`r data[14,4]`

`r data[15,4]`

`r data[16,4]`


\newpage

## `r data[1,5]`
```{r fig.width=0.3, fig.height=0.3,fig.align="left",echo=FALSE}
library(png)
library(grid)
img <- readPNG("LogoSMI/ABC_es.png")
grid.raster(img)
``` 
\ `r data[1,4]`

`r data[2,4]`

`r data[3,4]`

`r data[4,4]`

`r data[5,4]`

`r data[6,4]`

`r data[7,4]`

`r data[8,4]`

`r data[9,4]`

`r data[10,4]`

`r data[11,4]`

