---
title: ''
mainfont: PT Sans
fontsize: 11pt
linestretch: 0.85
classoption: a4paper,landscape,twocolumn
geometry:
  top=3cm,
  left=2cm,
  right=2cm,
  bottom=2cm
header-includes:
   - \usepackage{makecell}
   - \usepackage{hyperref}
   - \usepackage{newverbs}
   - \usepackage{color}
   - \usepackage[dvipsnames]{xcolor}
   - \definecolor{mycolor}{HTML}{2e75b5}
   - \definecolor{mycolor2}{HTML}{605F61}
   - \color{mycolor2}
output: 
  pdf_document:
    latex_engine: xelatex
params:
  data: NA
---

```{r setup, include=FALSE}
Sys.setlocale(,"UK_ua")
library(tidyverse)
```

```{r, include=FALSE}
#data <- readxl::read_excel("~/inputdata26.06 (1).xlsx")
#data <- input$data
data <- params$data
```

\vspace{12pt}

## НОВИНИ СВІТУ
\noindent

\begin{tabular}{rrc}
```{r, results='asis', echo=FALSE,warning=FALSE}
cat(for (i in which(data$Рубрика=="Новини світу")){
  cat(readLines("include.Rnw",encoding = "UTF-8"),
    ifelse(file.exists(paste0("LogoSMI/",tolower(data[[i,1]]),".png")),paste0("LogoSMI/",tolower(data[[i,1]]),".png"),"LogoSMI/inosmi_not_exist.png"),
readLines("end1.Rnw",encoding = "UTF-8"),"\n",
readLines("box3.Rnw",encoding = "UTF-8"),
readLines("box2.Rnw",encoding = "UTF-8"),
gsub(pattern = "#",replacement = readLines("hash.Rnw"),data[[i,3]]),"}{",
#toupper(data[[i,1]]),
readLines("par.Rnw",encoding = "UTF-8"),
#data[[i,2]],
#readLines("end1.Rnw",encoding = "UTF-8"),"\n",
paste0(data[[i,1]],"} "),
paste("|",data[[i,2]]),"}}}} ", readLines("ttttt.Rnw",encoding = "UTF-8")," ",
gsub(pattern = "%",replacement = readLines("percent.Rnw"),data[[i,4]]),
readLines("end2.Rnw",encoding = "UTF-8"),"\n",sep = "")
})
```
\end{tabular}

\newpage

## ЗАКОРДОННІ ЗМІ ПРО УКРАЇНУ
\noindent

\begin{tabular}{rc}
```{r, results='asis', echo=FALSE,warning=FALSE}
cat(for (i in which(data$Рубрика=="Закордонні ЗМІ про Україну")){
  cat(readLines("include.Rnw",encoding = "UTF-8"),
    ifelse(file.exists(paste0("LogoSMI/",tolower(data[[i,1]]),".png")),paste0("LogoSMI/",tolower(data[[i,1]]),".png"),"LogoSMI/inosmi_not_exist.png"),
readLines("end1.Rnw",encoding = "UTF-8"),"\n",
readLines("box3.Rnw",encoding = "UTF-8"),
readLines("box2.Rnw",encoding = "UTF-8"),
gsub(pattern = "#",replacement = readLines("hash.Rnw"),data[[i,3]]),"}{",
#toupper(data[[i,1]]),
readLines("par.Rnw",encoding = "UTF-8"),
#data[[i,2]],
#readLines("end1.Rnw",encoding = "UTF-8"),"\n",
paste0(data[[i,1]],"} "),
paste("|",data[[i,2]]),"}}}} ", readLines("ttttt.Rnw",encoding = "UTF-8")," ",
gsub(pattern = "%",replacement = readLines("percent.Rnw"),data[[i,4]]),
readLines("end2.Rnw",encoding = "UTF-8"),"\n",sep = "")
})
```
\end{tabular}

\pagenumbering{gobble} 
